### ISSUE TITLE
segfault on iofwrite

### ISSUE THREAD

**Issue by dromer** [casiojapi/vector-graphica#1]
On Debian Stable/11:

```gdb
Reading symbols from ./vector-graphica...
(gdb) run
Starting program: /home/dreamer/Sources/_downloads/vector-graphica/vector-graphica 
starting vector-graphica.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e26521 in __GI__IO_fwrite (buf=0x555555557056, size=1, count=3, fp=0x0) at iofwrite.c:37
37	iofwrite.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7e26521 in __GI__IO_fwrite (buf=0x555555557056, size=1, count=3, fp=0x0) at iofwrite.c:37
#1  0x00005555555554c9 in main ()
quit) 
```

**Comment by casiojapi** [comment]
Thank you for opening the issue. I believe It's an issue regarding cpu arch. I switched to another cpu architecture and It has been kinda difficult to port, regardless of the small size of the program. Will be working on making it compatible with any other arch soon.

**Comment by dromer** [comment]
Ok! I thought maybe it tries to open a file that does not exist. Haven't dived too deep into the program to see what it could be.
Hope it will work at some point, I like the idea of generating such random sphere images (and possibly other shapes in the future?).

**Comment by casiojapi** [comment]
Yep, the idea is to make all that stuff and many more. I also was thinking about porting it to Rust, WDYT?

About timing, on February I'll get more time to invest in the project, so prolly will advance on solving these issues and surely will be adding more features (like some better and useful command line arguments, maybe build a web-ui, and some more graphic stuff like other 3d shapes)

Do you have any suggestions?

**Comment by casiojapi** [comment]
> On Debian Stable/11:
> 
> ```gdb
> Reading symbols from ./vector-graphica...
> (gdb) run
> Starting program: /home/dreamer/Sources/_downloads/vector-graphica/vector-graphica 
> starting vector-graphica.
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff7e26521 in __GI__IO_fwrite (buf=0x555555557056, size=1, count=3, fp=0x0) at iofwrite.c:37
> 37	iofwrite.c: No such file or directory.
> (gdb) bt
> #0  0x00007ffff7e26521 in __GI__IO_fwrite (buf=0x555555557056, size=1, count=3, fp=0x0) at iofwrite.c:37
> #1  0x00005555555554c9 in main ()
> quit) 
> ```

Did you have the "renders" folder on the bin directory? That may have been the problem... Try it after creating the "renders" folder on the binary directory, or just clone the last commit from master.

**Comment by dromer** [comment]
@casiojapi hah, that was it :)

Now I just get black images, though.

**Comment by dromer** [comment]
oh, just pulled the latest commit. no longer entirely black:

![](https://i.imgur.com/ohotsgJ.png)

**Comment by casiojapi** [comment]
That's better hehe... Might be a bug with the lights... either they are completely no working or they are in the wrong position. Don't understand why that doesn't work on you. I'll try to get it. Thanks for reaching out!
